[project]
name = "polar-sheets"
version = "0.1.0"
description = "Testing Google Sheets to Polars DataFrame developer experience"
authors = ["oceanicsdotio"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
python = ">=3.10,<3.13"
polars = ">=1.17.0"

[pypi-dependencies]
gspread = ">=6.2.1"

[tasks]
main = "python main.py"
